pipeline {
    agent{
        label 'slave12'
    }
	stages{
		stage('test automation'){
			steps{
			
					sh 'python3 Reqres.py'
					
			}
		
		
		
		}
		
		stage('Test validation'){
			steps{
			
				sh 'pytest'
			}
			
		}
		
	}	
	

}
